#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────
# install.sh — Install the Timewarden SwiftBar plugin
#
# Usage:
#   ./install.sh                          # interactive
#   ./install.sh /path/to/timewarden.mobile  # non-interactive
# ─────────────────────────────────────────────────

PLUGIN_NAME="timewarden.30s.sh"
CACHE_DIR="$HOME/.cache/swiftbar-timewarden"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Timewarden SwiftBar Plugin — Installer"
echo "======================================="
echo ""

# ── 1. Verify SwiftBar is installed ────────────────
if ! command -v brew &>/dev/null; then
    echo "Error: Homebrew is required. Install from https://brew.sh"
    exit 1
fi

if [[ ! -d "/Applications/SwiftBar.app" ]]; then
    echo "SwiftBar not found. Installing via Homebrew..."
    brew install --cask swiftbar
    echo ""
fi

# ── 2. Detect SwiftBar plugins directory ───────────
PLUGIN_DIR=$(defaults read com.ameba.SwiftBar PluginDirectory 2>/dev/null || echo "")

if [[ -z "$PLUGIN_DIR" ]]; then
    echo "SwiftBar hasn't been configured yet."
    echo "Please launch SwiftBar once and set a plugin directory, then re-run this script."
    echo ""
    echo "  open -a SwiftBar"
    echo ""
    exit 1
fi

echo "SwiftBar plugins directory: $PLUGIN_DIR"

# ── 3. Resolve timewarden.mobile project path ──────
if [[ $# -ge 1 ]]; then
    PROJECT_PATH="$1"
else
    # Try to auto-detect
    candidate=$(find "$HOME/Developer" "$HOME/Projects" "$HOME/Code" "$HOME/repos" -maxdepth 2 -name "timewarden.mobile" -type d 2>/dev/null | head -1)
    if [[ -n "$candidate" ]]; then
        echo "Auto-detected project: $candidate"
        read -rp "Use this path? [Y/n] " confirm
        if [[ "${confirm:-Y}" =~ ^[Yy]?$ ]]; then
            PROJECT_PATH="$candidate"
        fi
    fi

    if [[ -z "${PROJECT_PATH:-}" ]]; then
        read -rp "Enter path to timewarden.mobile: " PROJECT_PATH
    fi
fi

# Resolve to absolute path
PROJECT_PATH=$(cd "$PROJECT_PATH" 2>/dev/null && pwd)

# Validate
if [[ ! -f "$PROJECT_PATH/run.sh" ]]; then
    echo "Error: $PROJECT_PATH doesn't look like a timewarden.mobile checkout (no run.sh found)"
    exit 1
fi

echo "Project path: $PROJECT_PATH"
echo ""

# ── 4. Write config ────────────────────────────────
mkdir -p "$CACHE_DIR"
cat > "$CACHE_DIR/config" << EOF
# Timewarden SwiftBar plugin config
# Generated by install.sh on $(date +%Y-%m-%d)
TIMEWARDEN_PROJECT="$PROJECT_PATH"
EOF

echo "Config written to $CACHE_DIR/config"

# ── 5. Install plugin ──────────────────────────────
mkdir -p "$PLUGIN_DIR"
cp "$SCRIPT_DIR/$PLUGIN_NAME" "$PLUGIN_DIR/$PLUGIN_NAME"
chmod +x "$PLUGIN_DIR/$PLUGIN_NAME"

echo "Plugin installed to $PLUGIN_DIR/$PLUGIN_NAME"

# ── 6. Clear icon cache (regenerate on first run) ──
rm -f "$CACHE_DIR/menubar.b64" "$CACHE_DIR/android.b64"
echo "Icon cache cleared (will regenerate on first refresh)"

# ── 7. Refresh SwiftBar ────────────────────────────
open "swiftbar://refreshallplugins" 2>/dev/null || true

echo ""
echo "Done! The Timewarden icon should appear in your menu bar."
echo "If SwiftBar isn't running, start it with: open -a SwiftBar"
